#------------------------------------
# Birkin Max
#------------------------------------
name: CI-CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Print Dart SDK version
        run: echo "Привет"
  deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Print Dart SDK version
        run: echo "Привет"